# Generated by Django 6.1.1 on 2026-09-17 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='business_problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dataset',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='insights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='methodology',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='results',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='project_files/')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
            ],
        ),
    ]
