# Generated by Django 6.1.1 on 2026-09-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
                ('professional_summary', models.TextField()),
                ('career_objective', models.TextField()),
                ('what_i_do', models.TextField()),
                ('my_approach', models.TextField()),
            ],
        ),
    ]
